set(ASAN OFF)
set(UBSAN OFF)
set(DIST ON)

set(NONET ON)
set(PACKET_ENCRYPTION OFF)
set(DEFAULT_PER_PIXEL_LIGHTING false)

set(DEVILUTIONX_SYSTEM_BZIP2 OFF)
set(DEVILUTIONX_SYSTEM_ZLIB OFF)
set(DEVILUTIONX_STATIC_ZLIB ON)
set(USE_SDL3 ON)
set(DEVILUTIONX_SYSTEM_SDL3 OFF)
set(DEVILUTIONX_STATIC_SDL3 ON)
set(DEVILUTIONX_SYSTEM_SDL_IMAGE OFF)
set(DEVILUTIONX_SYSTEM_LIBPNG OFF)

# Audio settings for DOS port
set(DEVILUTIONX_SYSTEM_SDL_MIXER OFF)
set(DEFAULT_AUDIO_SAMPLE_RATE 22050)
set(DEFAULT_AUDIO_CHANNELS 2)
set(DEFAULT_AUDIO_BUFFER_SIZE 1024)
set(DEVILUTIONX_DISPLAY_PIXELFORMAT SDL_PIXELFORMAT_INDEX8)

set(DEVILUTIONX_PLATFORM_FILE_UTIL_LINK_LIBRARIES "")

list(APPEND DEVILUTIONX_PLATFORM_COMPILE_OPTIONS $<$<CONFIG:Debug>:-gstabs>)

add_compile_definitions(
  SDL_DISABLE_SSE
  SDL_DISABLE_SSE2
  SDL_DISABLE_SSE3
  SDL_DISABLE_SSE4_1
  SDL_DISABLE_SSE4_2
)
