SET(MINGW_CROSS TRUE)

# Toolchain built by Packaging/windows/mingwxp-prep.sh
SET(CROSS_PREFIX "/opt/mingwxp" CACHE STRING "mingwxp toolchain prefix")

SET(MINGWXP_TRIPLET "i686-w64-mingw32")

SET(CMAKE_SYSTEM_NAME Windows)

# workaround
list(APPEND CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "${CROSS_PREFIX}/${MINGWXP_TRIPLET}/include")

SET(CMAKE_C_COMPILER   "${CROSS_PREFIX}/bin/${MINGWXP_TRIPLET}-gcc")
SET(CMAKE_CXX_COMPILER "${CROSS_PREFIX}/bin/${MINGWXP_TRIPLET}-g++")
set(CMAKE_RC_COMPILER "${CROSS_PREFIX}/bin/${MINGWXP_TRIPLET}-windres")
set(CMAKE_STRIP "${CROSS_PREFIX}/${MINGWXP_TRIPLET}/bin/strip")
set(PKG_CONFIG_EXECUTABLE "${CROSS_PREFIX}/bin/${MINGWXP_TRIPLET}-pkg-config" CACHE STRING "Path to pkg-config")

SET(CMAKE_FIND_ROOT_PATH  "${CROSS_PREFIX}/${MINGWXP_TRIPLET}" "${CROSS_PREFIX}/${MINGWXP_TRIPLET}/${MINGWXP_TRIPLET}")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(WIN32_INSTALL_DLLS "${CROSS_PREFIX}/${MINGWXP_TRIPLET}/bin/SDL2.dll")
