SET(MINGW_CROSS TRUE)

# Toolchain built by Packaging/windows/mingw9x-prep.sh
SET(CROSS_PREFIX "/opt/mingw9x" CACHE STRING "mingw9x toolchain prefix")

# i586 (plain Pentium) baseline: Windows 98-era CPUs may lack cmov.
SET(MINGW9X_TRIPLET "i586-w64-mingw32")

SET(CMAKE_SYSTEM_NAME Windows)

# workaround
list(APPEND CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "${CROSS_PREFIX}/${MINGW9X_TRIPLET}/include")

list(PREPEND CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/mingw9x/include")
list(PREPEND CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/mingw9x/include")

# work around https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106103
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "${CMAKE_CXX_FLAGS_MINSIZEREL_INIT} -fno-declone-ctor-dtor")

SET(CMAKE_C_COMPILER   "${CROSS_PREFIX}/bin/${MINGW9X_TRIPLET}-gcc")
SET(CMAKE_CXX_COMPILER "${CROSS_PREFIX}/bin/${MINGW9X_TRIPLET}-g++")
set(CMAKE_RC_COMPILER "${CROSS_PREFIX}/bin/${MINGW9X_TRIPLET}-windres")
set(CMAKE_STRIP "${CROSS_PREFIX}/${MINGW9X_TRIPLET}/bin/strip")
set(PKG_CONFIG_EXECUTABLE "${CROSS_PREFIX}/bin/${MINGW9X_TRIPLET}-pkg-config" CACHE STRING "Path to pkg-config")

SET(CMAKE_FIND_ROOT_PATH  "${CROSS_PREFIX}/${MINGW9X_TRIPLET}" "${CROSS_PREFIX}/${MINGW9X_TRIPLET}/${MINGW9X_TRIPLET}")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(WIN32_INSTALL_DLLS "${CROSS_PREFIX}/${MINGW9X_TRIPLET}/bin/SDL.dll")
